
version: "3"

tasks:
  migrate:
    aliases:
      - migrations
    desc: "Migration db"
    cmds:
      - migrate -path ./migrations/ -database "postgresql://postgres:12345678@localhost:5432/postgres?sslmode=disable" up
  table_down:
    aliases:
      - migrations
    desc: "table down"
    cmds:
      - migrate -path ./migrations/ -database "postgresql://postgres:12345678@localhost:5432/postgres?sslmode=disable" down
  generate:
    aliases:
      - pkg
    desc: "Generate code from proto files"
    cmds:
      - protoc -I api api/*.proto --go_out=./pkg/auth/ --go_opt=paths=source_relative --go-grpc_out=./pkg/auth/ --go-grpc_opt=paths=source_relative